SET SAFETY OFF
SET TALK OFF
*** programa limpia Tablas  - todas  ****
USE variables EXCLUSIVE
zap
REPLACE variables.congapls WITH "S0", variables.congapla WITH "A0" , variables.num_fecha WITH 0, ;
    variables.codcomp WITH 0

USE APLICA EXCLUSIVE
ZAP
USE CREDITO EXCLUSIVE
ZAP
USE DCREDITO EXCLUSIVE
ZAP
USE JORCULTI EXCLUSIVE
ZAP
USE LOTESFIN EXCLUSIVE
ZAP
USE INFCULTI EXCLUSIVE
ZAP
USE INSAPLICA EXCLUSIVE
ZAP
USE LABCULTI EXCLUSIVE
ZAP

**** PARA QUE PUEDA GRABAR EN JORCULTI HAY MANTENER ESTOS CODIGOS
**** QUE SON CERO
USE UBICA EXCLUSIVE
DELETE FOR UBICA.codfin > 0
PACK

USE IPROV EXCLUSIVE
DELETE FOR IPROV.codprov > 1
PACK

USE INSUMO EXCLUSIVE
*delete for nominsum<>"EMPAQUE" and nominsum<>"CABUYA"  and nominsum<>"FEDEARROZ"
DELETE FOR INSUMO.codinsum > 1
PACK

USE VENTAS EXCLUSIVE
ZAP
USE PROCION EXCLUSIVE
ZAP

USE Años EXCLUSIVE
ZAP
USE Costot EXCLUSIVE
ZAP

USE Renren EXCLUSIVE
ZAP
USE plub EXCLUSIVE
ZAP

USE finplu EXCLUSIVE
ZAP
USE finvaraño EXCLUSIVE
ZAP
USE varaños EXCLUSIVE
ZAP

USE regfin EXCLUSIVE
ZAP
USE rendim EXCLUSIVE
ZAP
USE finren EXCLUSIVE
ZAP
USE finaño EXCLUSIVE
ZAP
USE ldrf EXCLUSIVE
ZAP
USE INFCULTI EXCLUSIVE
ZAP
USE fcaja EXCLUSIVE
ZAP

USE teminvp EXCLUSIVE
ZAP
USE Renren EXCLUSIVE
ZAP
USE COMPP1  EXCLUSIVE
ZAP
USE ldrtc EXCLUSIVE
ZAP
USE finpxc EXCLUSIVE
ZAP

**** limpieza de campos ****

USE CULTIVO
REPLACE ALL nat1 WITH ""
REPLACE ALL nat2 WITH ""
REPLACE ALL nat3 WITH ""
REPLACE ALL nat4 WITH ""
REPLACE ALL cosven WITH ""
REPLACE ALL ingven WITH ""
REPLACE ALL salicult WITH ""
REPLACE ALL guia1 WITH ""
REPLACE ALL guia1 WITH ""
REPLACE ALL guia2 WITH ""
REPLACE ALL guia3 WITH ""

USE ciclos
REPLACE fechai WITH CTOD("//") ALL
REPLACE fecha1 WITH CTOD("//") ALL
REPLACE fecha2 WITH CTOD("//") ALL
REPLACE fecha3 WITH CTOD("//") ALL
REPLACE fecha4 WITH CTOD("//") ALL
REPLACE fecha5 WITH CTOD("//") ALL
REPLACE cierr WITH 0 ALL

USE Cospor EXCLUSIVE
UPDATE Cospor SET porc1 = 0, porc2 = 0, porc3 = 0, porc4 = 0, ;
    porc5 = 0, porc6 = 0, porc7 = 0, porc8 = 0, porc9 = 0,  porc10 = 0

CLEAR ALL
