SELECT PUC1

SET STEP ON
DO WHILE !EOF()
    V_VIE = RIGHT(LEFT(CODCONTABL,8),2)
    IF !EMPTY(V_VIE)
        V_CAM = VAL(aLLTRIM(V_VIE))/5
        REPLACE CODCONTABL WITH LEFT(CODCONTABL,6) ;
        + IIF(LEN(ALLTRIM(STR(V_CAM)))= 2,;
        aLLTRIM(STR(V_CAM)),"0"+ALLTRIM(STR(V_CAM)))  
    ENDIF
    SKIP
ENDDO
